# Generated by Django 3.0 on 2020-09-09 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_auto_20200903_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug_name',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Can not have spaces.', regex='^[a-zA-Z0-9]$')]),
        ),
    ]
