# Generated by Django 3.0 on 2020-09-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Updated at')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('num_weeks', models.PositiveIntegerField(default=0, verbose_name='Number weeks paid')),
                ('payment_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(verbose_name='expire')),
                ('is_active', models.BooleanField(default=False)),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Client')),
                ('paid_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.Gym')),
            ],
            options={
                'ordering': ['created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
